"""
portal_schemas/compliance.py - Pydantic models for AquaGuard Portal.

Defines schemas for water sensors, reasoning states, hardware controls, and regional council audit logs.
"""

from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional
from pydantic import BaseModel, Field


class AerationAction(str, Enum):
    """Aerator control levels."""
    OFF = "off"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class PumpAction(str, Enum):
    """Water circulation control levels."""
    OFF = "off"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class ValveAction(str, Enum):
    """Effluent or drain valve control states."""
    OPEN = "open"
    CLOSED = "closed"


class WaterSensorReading(BaseModel):
    """
    Standard schema for water telemetry readings (e.g. pH, DO, Temp, Turbidity, Nitrate).
    """
    sensor_id: str = Field(..., description="Unique sensor identifier (e.g. 'ph_sensor_1')")
    sensor_type: str = Field(..., description="Type of sensor (e.g. 'pH', 'DO', 'temperature', 'turbidity', 'nitrate')")
    value: float = Field(..., description="Numerical reading value")
    unit: str = Field(..., description="Unit of measurement (e.g. 'pH', 'mg/L', 'C', 'NTU')")
    timestamp: datetime = Field(default_factory=datetime.now)


class WaterAnalysisResult(BaseModel):
    """
    LLM reasoning results of current water parameters.
    """
    analysis_id: str = Field(..., description="Unique analysis identifier")
    status: str = Field(..., description="Overall health assessment (healthy, warning, critical)")
    ph_trend: str = Field(..., description="pH direction (stable, increasing, decreasing)")
    do_trend: str = Field(..., description="Dissolved Oxygen direction (stable, increasing, decreasing)")
    temperature_trend: str = Field(..., description="Temperature direction (stable, increasing, decreasing)")
    turbidity_trend: str = Field(..., description="Turbidity direction (stable, increasing, decreasing)")
    nitrate_trend: str = Field(..., description="Nitrate trend direction (stable, increasing, decreasing)")
    visual_observations: Optional[str] = Field(None, description="Observations from video frames (clarity, behavior)")
    audio_observations: Optional[str] = Field(None, description="Acoustic detections (vibrations, leaks)")
    timestamp: datetime = Field(default_factory=datetime.now)


class WaterOptimizationPlan(BaseModel):
    """
    Action commands generated by LLM reasoning. Converted to real or mock hardware outputs.
    """
    plan_id: str = Field(..., description="Unique plan identifier")
    generated_at: datetime = Field(default_factory=datetime.now)
    
    # Actuator states
    aeration_action: AerationAction = Field(..., description="Target aerator intensity")
    pump_action: PumpAction = Field(..., description="Target pump speed")
    valve_action: ValveAction = Field(..., description="Target valve state")

    # Explanations & logs
    confidence_score: float = Field(..., ge=0.0, le=1.0, description="Model confidence in the plan (0.0 - 1.0)")
    logistical_notes: Optional[str] = Field(None, description="Operational notes or warnings")
    execution_window_minutes: int = Field(..., description="Validity window for this plan")
    requires_human_review: bool = Field(default=False, description="Flag if manual sign-off is needed")

    class Config:
        json_schema_extra = {
            "example": {
                "plan_id": "opt-water-2026-06-07-001",
                "generated_at": "2026-06-07T16:00:00Z",
                "aeration_action": "high",
                "pump_action": "medium",
                "valve_action": "closed",
                "confidence_score": 0.95,
                "logistical_notes": "Dissolved oxygen falling below critical 5.0mg/L threshold; activating aerators.",
                "execution_window_minutes": 15,
                "requires_human_review": False,
            }
        }


class ComplianceRecord(BaseModel):
    """
    Strict schema representing a single audit log suitable for NZ Regional Council compliance inspections.
    """
    audit_id: str = Field(..., description="Unique audit record identifier")
    timestamp: datetime = Field(default_factory=datetime.now)
    regional_council: str = Field(..., description="Name of the targeted regional council (e.g. Horizons, Waikato)")
    consent_id: str = Field(..., description="Resource consent authorization identifier (e.g. CONSENT-2026-AUTH-0981)")
    status: str = Field(..., description="Compliance status (compliant, breach_warning, breach_critical)")
    metrics: Dict[str, float] = Field(..., description="Current water metrics (pH, DO, temp, turbidity, nitrate)")
    actions_taken: List[str] = Field(..., description="List of physical commands executed during this interval")
    operator_notes: Optional[str] = Field(None, description="System or operator notes detailing the state")
